name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cache cargo deps
      uses: actions/cache@v3
      with:
        path: target/debug/deps
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-    
    
    - name: cargo build
      run: cargo build --verbose

    - name: cargo test
      run: cargo test --verbose
